/**
 * Structural contracts for the metadata files M1 classifies as class ②.
 *
 * These paths (package.json, package-lock.json, .qoder-plugin/plugin.json, docs,
 * SKILL.md prose) collide with the ancestor hop but have no honest behavioural
 * test -- a wrong string in them is not a behaviour. The ralplan therefore asks
 * for structural assertions instead of invented tests: each rule below states a
 * property the adoption must keep true, and each one fails if a future change
 * quietly breaks it.
 */
import { describe, expect, it } from 'vitest';
import { existsSync, readdirSync, readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const repoRoot = join(dirname(fileURLToPath(import.meta.url)), '..', '..');
const readJson = (relativePath: string) =>
  JSON.parse(readFileSync(join(repoRoot, relativePath), 'utf8')) as Record<string, any>;

const pkg = readJson('package.json');
const plugin = readJson('.qoder-plugin/plugin.json');

describe('package.json payload contract', () => {
  // The installer copies the package as-is and runs no build, so anything not
  // listed here is simply absent from what a user gets. NOTICE matters because
  // the ancestor is MIT-licensed and attribution rides in the payload.
  it('ships every directory the plugin manifest and runtime depend on', () => {
    const required = [
      'dist', 'bridge', 'bin', 'scripts', 'skills', 'commands', 'hooks',
      'agents', 'templates', 'docs', '.qoder-plugin', 'README.md', 'LICENSE', 'NOTICE',
    ];
    for (const entry of required) {
      expect(pkg.files, `files whitelist is missing ${entry}`).toContain(entry);
    }
  });

  it('does not ship the TypeScript sources that the whitelist would expose', () => {
    expect(pkg.files).not.toContain('src');
  });

  it('points every hand-written bin target at a file that exists', () => {
    // bridge/cli.cjs is generated by the build, so it is checked by the payload
    // gate in CI rather than here.
    for (const [name, target] of Object.entries(pkg.bin as Record<string, string>)) {
      if (target.startsWith('bridge/')) continue;
      expect(existsSync(join(repoRoot, target)), `bin.${name} -> ${target} does not exist`).toBe(true);
    }
  });

  it('declares the generated bridge entry it expects the build to produce', () => {
    expect(Object.values(pkg.bin as Record<string, string>)).toContain('bridge/cli.cjs');
    expect(pkg.files).toContain('bridge');
  });
});

describe('package-lock.json registry contract', () => {
  const lock = readFileSync(join(repoRoot, 'package-lock.json'), 'utf8');
  const hosts = [...lock.matchAll(/"resolved":\s*"(https?:\/\/[^/"]+)/g)].map((m) => m[1]);

  it('resolves every dependency from the public registry', () => {
    expect(hosts.length, 'no resolved URLs found -- the pattern no longer matches the lockfile').toBeGreaterThan(0);
    expect([...new Set(hosts)]).toEqual(['https://registry.npmjs.org']);
  });

  it('carries no internal or corporate registry host', () => {
    expect(lock).not.toMatch(/alibaba|anpm|\.corp\b|nexus|artifactory|127\.0\.0\.1|localhost/i);
  });
});

describe('plugin manifest contract', () => {
  const skillDirs = readdirSync(join(repoRoot, 'skills'), { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .map((entry) => `./skills/${entry.name}/`)
    .sort();

  // Qoder loads what the manifest lists. An entry with no directory is dead
  // weight; a directory with no entry never loads and looks like it was dropped.
  it('lists exactly the skills that exist on disk', () => {
    const listed = [...plugin.skills].sort();
    expect(listed.filter((s: string) => !skillDirs.includes(s)), 'listed but absent from disk').toEqual([]);
    expect(skillDirs.filter((s) => !listed.includes(s)), 'on disk but not listed').toEqual([]);
    expect(listed.length).toBe(skillDirs.length);
  });

  it('gives every listed skill a SKILL.md', () => {
    for (const entry of plugin.skills as string[]) {
      expect(existsSync(join(repoRoot, entry, 'SKILL.md')), `${entry} has no SKILL.md`).toBe(true);
    }
  });

  // Verified against a real install: `commands` is a directory string, not an
  // array. A previous plan assumed an array and would have "fixed" this wrongly.
  it('keeps commands as the directory form the loader expects', () => {
    expect(typeof plugin.commands).toBe('string');
    expect(plugin.commands).toBe('./commands/');
  });

  it('names the plugin without a marketplace slug that only fits one product', () => {
    expect(typeof plugin.name).toBe('string');
    expect(plugin.name).toBe('oh-my-qoder');
    expect(plugin.name).not.toMatch(/^(omq|local)$/);
  });
});
