/**
 * Drift check for the generated workflow-stage prompt artifacts.
 *
 * scripts/lib/workflow-stage-prompts.mjs and its mirror under
 * templates/hooks/lib/ are GENERATED files (see the "Do not edit this file
 * directly" banner) produced by scripts/build-workflow-stage-prompts.mjs from
 * the canonical TypeScript stage adapters in src/hooks/autopilot/.
 *
 * 47b7c74 changed the source without re-running the generator; the committed
 * artifacts kept pointing at an unresolvable subagent namespace until
 * 6cd3d15 regenerated them by hand two days later. These tests turn that
 * state red: run `node scripts/build-workflow-stage-prompts.mjs` whenever
 * they fail.
 *
 * The build script is a write-to-disk one-shot (it also reads the compiled
 * dist/ tree), so the transformation is replicated here IN MEMORY from the
 * TypeScript adapters directly — a source edit invalidates the committed
 * artifacts immediately, without waiting for a dist rebuild.
 */
import { readFileSync } from "node:fs";
import { createHash } from "node:crypto";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, it, expect } from "vitest";
import { getAdapterById } from "../hooks/autopilot/adapters/index.js";
import { DEFAULT_PIPELINE_CONFIG } from "../hooks/autopilot/pipeline-types.js";

const root = join(dirname(fileURLToPath(import.meta.url)), "..", "..");

const taskToken = "__OMQ_NAMED_WORKFLOW_TASK__";
const taskDisplayToken = "__OMQ_NAMED_WORKFLOW_TASK_DISPLAY__";
const analystPromptToken = "__OMQ_NAMED_WORKFLOW_ANALYST_PROMPT__";
const architectPromptToken = "__OMQ_NAMED_WORKFLOW_ARCHITECT_PROMPT__";

function serializeTaskContexts(prompt: string): string {
  const serialized = prompt
    .replaceAll(
      `**Original Idea:** "${taskToken}"`,
      `**Original Idea:**\n\n    ${taskDisplayToken}`,
    )
    .replace(
      `prompt="REQUIREMENTS ANALYSIS for: ${taskToken}\n\nExtract and document:\n1. Functional requirements (what it must do)\n2. Non-functional requirements (performance, UX, etc.)\n3. Implicit requirements (things user didn't say but needs)\n4. Out of scope items\n\nOutput as structured markdown with clear sections."`,
      `prompt=${analystPromptToken}`,
    )
    .replace(
      `prompt="TECHNICAL SPECIFICATION for: ${taskToken}\n\nBased on the requirements analysis above, create:\n1. Tech stack decisions with rationale\n2. Architecture overview (patterns, layers)\n3. File structure (directory tree)\n4. Dependencies list (packages)\n5. API/interface definitions\n\nOutput as structured markdown."`,
      `prompt=${architectPromptToken}`,
    );
  if (serialized.includes(taskToken)) {
    throw new Error(
      "Unclassified named workflow task placeholder in stage prompt",
    );
  }
  return serialized;
}

const stages = ["ralplan", "execution", "ralph", "qa"];
const prompts = Object.fromEntries(
  stages.map((stage) => [
    stage,
    serializeTaskContexts(
      getAdapterById(stage)!.getPrompt({
        idea: taskToken,
        directory: ".",
        config: DEFAULT_PIPELINE_CONFIG,
      }),
    ),
  ]),
);

const generated = `// Generated by scripts/build-workflow-stage-prompts.mjs from the canonical TypeScript stage adapters.\n// Do not edit this file directly.\n\nconst TASK_DISPLAY_TOKEN = ${JSON.stringify(taskDisplayToken)};\nconst ANALYST_PROMPT_TOKEN = ${JSON.stringify(analystPromptToken)};\nconst ARCHITECT_PROMPT_TOKEN = ${JSON.stringify(architectPromptToken)};\nconst PROMPTS = Object.freeze(${JSON.stringify(prompts, null, 2)});\n\nfunction analystPrompt(task) {\n  return \`REQUIREMENTS ANALYSIS for: \${task}\\n\\nExtract and document:\\n1. Functional requirements (what it must do)\\n2. Non-functional requirements (performance, UX, etc.)\\n3. Implicit requirements (things user didn't say but needs)\\n4. Out of scope items\\n\\nOutput as structured markdown with clear sections.\`;\n}\n\nfunction architectPrompt(task) {\n  return \`TECHNICAL SPECIFICATION for: \${task}\\n\\nBased on the requirements analysis above, create:\\n1. Tech stack decisions with rationale\\n2. Architecture overview (patterns, layers)\\n3. File structure (directory tree)\\n4. Dependencies list (packages)\\n5. API/interface definitions\\n\\nOutput as structured markdown.\`;\n}\n\nexport function resolveCanonicalWorkflowStagePrompt(stageId, task) {\n  const prompt = PROMPTS[stageId];\n  if (typeof prompt !== 'string' || typeof task !== 'string' || task.trim().length === 0) return null;\n  const normalizedTask = task.trim();\n  const replacements = {\n    [TASK_DISPLAY_TOKEN]: JSON.stringify(normalizedTask),\n    [ANALYST_PROMPT_TOKEN]: JSON.stringify(analystPrompt(normalizedTask)),\n    [ARCHITECT_PROMPT_TOKEN]: JSON.stringify(architectPrompt(normalizedTask)),\n  };\n  return prompt.replace(/__OMQ_NAMED_WORKFLOW_(?:TASK_DISPLAY|ANALYST_PROMPT|ARCHITECT_PROMPT)__/g, (token) => replacements[token]);\n}\n`;

function sha256(content: string): string {
  return createHash("sha256").update(content).digest("hex");
}

const libArtifact = "scripts/lib/workflow-stage-prompts.mjs";
const mirrorArtifact = "templates/hooks/lib/workflow-stage-prompts.mjs";
const rerunHint =
  "Run: node scripts/build-workflow-stage-prompts.mjs (regenerates both artifacts)";

describe("workflow-stage-prompts drift check", () => {
  it("in-memory generation matches the committed scripts/lib artifact byte-for-byte", () => {
    const committed = readFileSync(join(root, libArtifact), "utf8");
    expect(generated).toEqual(committed);
    expect(sha256(generated)).toBe(sha256(committed));
  });

  it("in-memory generation matches the committed templates/hooks/lib mirror byte-for-byte", () => {
    const committed = readFileSync(join(root, mirrorArtifact), "utf8");
    expect(generated).toEqual(committed);
    expect(sha256(generated)).toBe(sha256(committed));
  });

  it("the two committed artifacts are byte-identical to each other", () => {
    const lib = readFileSync(join(root, libArtifact), "utf8");
    const mirror = readFileSync(join(root, mirrorArtifact), "utf8");
    expect(`${lib}` === `${mirror}`, rerunHint).toBe(true);
    expect(sha256(mirror)).toBe(sha256(lib));
  });
});
